name: Sync Discord Roles

on:
  # Trigger on push
  push:
    branches: master

  # Run hourly
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    name: Sync discord rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-ruby@v1
      - uses: actions/checkout@v1
      - run: gem install bundler
      - run: bundle install --verbose
      - run: make sync_roles
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          REALLY_SYNC: true
